language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: collin@brewer-collective.com
  api_key:
    secure: iXujP5fbrocGZbG+X4lVHMuzLJEfmK21vHbzNC0n4LmToEB4wBHTRac04/KZIlI7CZ0/cNGOteUMDYha1HKuqJQJCiBr/vNA8e/eJeQxwrZUjubMX8rPT0/+pplFL/bWH1agwFoAGrdPWPBJfzB7tLnXO1w+1bZfKjYuIsyG/ZGPJq4jHaHFgLZaSPP2aiV56AuR8XT4ffnBgANKKoN8/WiwSLPhmo1GfIX1Elp1fgWHS95N0exFOoh1/0Fr/ehCR2/CaYaShZv/qBeHYVo6uJIiOwp0mDdiOKrw+tN+0jW2lnyqUzUAUtlHrVc9Vc77hZXs9ZdByPIDL56gPmkYRQg0pQraWDIZFp+Fg2muuupiyskD0cJ+hyBrBJdtmU+1OTMhANEdfN2iiF9hxwl1Ap7TNbasG+9mFgReuV+Alu7XVNfLWBflkWDgTEKkebuNnhPEmuN3gdCDMP/lSgH8bwLO4clxhp1ksn5ZGr3G6erPbitHvy2E2JZ/AbSIc38VgEI3TFz91vDKxpIqujRAI6aMgWMjt1np4bZ0NlBZcrO8Se/l/mcm+sGUTialKIdRa9032SI5K7zh7r/gfd845Z8lJ1sBi326ANzpS0E/UlIkl0HaV1md6yLDBn2RwdzrOyI2c0ly7YpmgOMjnFyPgQH18eXXKFAu8xI6hMCjJdE=
  on:
    tags: true
    repo: collinbrewer/react-schema-ui
after_script:
- npm run test:cov
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
